[basic]
sample_method = "gs"
process = "ecrp"
alpha = 5
n_trials = 10
n_iters = 200
array_size = 0x100
beta_exp_min = 0.0
beta_exp_max = 4.0

[fixed]
sample_method = "gs"
process = "ecrp_fixed"
alpha = 5
n_trials = 200
n_iters = 0x100
array_size = 0x10
beta_exp_min = 0.0
beta_exp_max = 4.0
